### ISSUE TITLE
rate on total_traffic in prometheus metric is crap

### ISSUE THREAD

**Issue by simonkurka** [hopglass/hopglass-server#46]
If there is a device reporting a totally new traffic value to hopglass-server (some values not reported or a new device) and we try to calculate a rate from it, there can be peaks, which are obviously wrong.

The error is logically explainable:
There is just a new or unusual high summand which can't be recognized by prometheus.
A workaround is to sum the rates of single nodes, but this gives a heavy load to grafana clients.

I don't have a practical solution yet, but maybe someone has a good idea?

**Comment by plumpudding** [comment]
A few ideas:
1) you can let Prometheus calculate the single nodes' rates when it queries the data
2) HG Server could calculate the deltas in the metrics and add them together for the total value

**Comment by simonkurka** [comment]
I don't see a possibility for 1) in Prometheus.

For 2) we need receiver data for, lets say t-1, and t to calculate data. I think it's not a solution to cache the last traffic data in provider module, because if someone calls getMetrics always just before a productive Prometheus, the bandwidth would be always 0. (because t-1 = t)

**Comment by mar-v-in** [comment]
@simonkurka if you want global traffic statistics, you can add rules to prometheus:

```
total_traffic_rx_bits_per_second{} = sum(rate(statistics_traffic{mtype="user",type="rx"}[3m])) * 8
total_traffic_tx_bits_per_second{} = sum(rate(statistics_traffic{mtype="user",type="tx"}[3m])) * 8
```

This way, the heavy calculation is only done once (when new data is added), instead of a lot (for all time displayed for each user displaying it). 
Note that 3m is assuming you are using 60s as refresh for statistics in hopglass-server and you will not loose more than one request in series. If you do nonetheless, it might happen that the projected bitrate is a bit off, but we see overall very good results with our setup.
