### ISSUE TITLE
L2TP tunnel detection

### ISSUE THREAD

**Issue by plumpudding** [hopglass/hopglass-server#55]
The problem is that data from L2TP nodes isn't reliable. The tunneldigger package hasn't implemented respondd stuff yet so it doesn't send any data when used in combination with gluon v2015.something or later. This breaks uplink detection and - in some cases - vpn link detection. 
If one side reports L2TP that must be the preferred over the other. The other side must also receive uplink status. 

ping @mar-v-in 
I would appreciate a new PR to fix this. I won't write any code this week.

**Comment by mar-v-in** [comment]
Yes, uplink status flag is not set correctly with l2tp.

I am not sure if I understand your problem correctly. The implementation in #52 does prefer proper link information from one side over less advanced information on the other side. I noticed that tunneldigger package does not support respondd as well.
I wonder what respondd server you use on the gateways causing such problems. It should report sth like this (of course not all fields)
```json
{ "nodeinfo": { "network": { "mesh": { "bat0": {
    "tunnel": [ "mac addresses of unknown batman lower devices that are assumed to be tunnels (will cause heuristic and fallback to VPN)" ],
    "l2tp": [ "mac addresses of batman lower devices that are exclusively used for l2tp" ],
    "fastd": [ "mac addresses of batman lower devices that are exclusively used for fastd" ],
    "gre": [ "mac addresses of batman lower devices that are exclusively used for gre (must be announced on both ends)" ],
    "wireless": [ "mac addresses of batman lower devices for wireless links" ],
    "other": [ "mac addresses of batman lower devices for directly wired links" ]
}}}}}
```
The idea for the heuristic on tunnel is, that I know there are some implementations of respondd for the gateway that does not differentiate between link types (because this makes things a lot easier) or by design cannot differentiate (when fastd and l2tp devices are put in a bridge and thus only one mac address appears in batman). As long as those announce "tunnel" for everything, it should be fine.

As l2tp/tunneldigger nodes using latest gluon and tunneldigger package from ffrl will report "other" and no meta information, it is crucial that the other side (gateway) does give proper information. The only possible work-around is a new heuristic: if one side reports "other" and the other side does not report anything, consider it "tunnel" (unknown VPN). This is a terrible heuristic but at least will cause l2tp vpn links to show up as VPN and not as wired.

Note that even if you have a proper respondd on gateway it might happen that no data is reported from it if you put l2tp devices from tunneldigger directly as batman lower devices, because the corresponding mac addresses were not in nodeinfo when it was requested last time. Also for other reasons it might be a good idea to use a bridge and connect l2tp devices to that one.

Do you have a concrete hopglass-server running somewhere that causes problematic output, so I can grab its raw.json while working on a fix?

**Comment by mar-v-in** [comment]
@plumpudding I don't know if you were referring to https://forum.freifunk.net/t/hopglass-server-aliases-json-linux-gateway/11518/36, but at least for them the problem seems to be the incomplete aliases.json.

Nonetheless, the missing uplink=true flag on l2tp nodes is a problem I will tackle this weekend.

**Comment by plumpudding** [comment]
What would I have to change with this aliases:
https://github.com/eulenfunk/mapconfig/blob/master/aliases/dus.json

**Comment by mar-v-in** [comment]
What is wrong there? (or did you solve it already?)

**Comment by plumpudding** [comment]
No, the uplinks are not displayed in the graph.

**Comment by plumpudding** [comment]
fixed
