### ISSUE TITLE
all nodes are doubled

### ISSUE THREAD

**Issue by rubo77** [hopglass/hopglass-server#71]
We installed the hs and it seems to work everything, but on our map all nodes are double with slightly different TQ values: https://map.freifunk.in-kiel.de/#!v:m;n:687251221506

You need to add this line to your /etc/hosts to see the site:

    138.201.16.163  map.freifunk.in-kiel.de hopglass.freifunk.in-kiel.de

**Comment by sargon** [comment]
That's not completely correct. Not the nodes itself are doubled in the general overview, but in a link list of a node, some links to nodes are doubled. And yes those double listed once state different TQ values for each link. First we thought this is because some of them "see" each other by wifi and by cable. But those special case then have listed the linked node four times.

https://map.freifunk.in-kiel.de/#!v:m;n:dc9fdb936465 is an extrem example of that behaviour. 
I just rewired dns entries for {map,hopglass}.freifunk.in-kiel.de.

**Comment by plumpudding** [comment]
Right, these are the different directions of the connection.

**Comment by rubo77** [comment]
So this is the intended behaviour?

Maybe we should somehow compact the View then. The name doesn't have to be double
