### ISSUE TITLE
gluon-respondd-airtime support

### ISSUE THREAD

**Issue by mweinelt** [hopglass/hopglass-server#78]
@corny developed the gluon-respondd-airtime package, which was documented here: https://github.com/freifunk-gluon/gluon/pull/826

Hopglass-server should add support, as seen in the respond-collector, to calculate the utilization between the update cycles.

https://github.com/FreifunkBremen/respond-collector/blob/ab01eb0d9ef3f33923982b0e7440c4461e6b9cc3/data/airtime.go#L49

**Comment by corny** [comment]
Pull Request for the Gluon package: https://github.com/freifunk-gluon/packages/pull/156

Example data:
```json
{
  "statistics": {
    "wireless": [
      {
        "frequency": 5220,
        "active": 366561161,
        "busy": 46496566,
        "rx": 808415,
        "tx": 41711344,
        "noise": 162
      },
      {
        "frequency": 2437,
        "active": 366649704,
        "busy": 205221222,
        "rx": 108121446,
        "tx": 85453679,
        "noise": 161
      }
    ]
  }
}
```

**Comment by mar-v-in** [comment]
What do these numbers represent and how should they finally be displayed is hopglass? 

I guess active is total active time of the wifi chip on that freq, rx is some time receiving (receiving as in packet targets this phy by SSID or all packets arriving) and tx is time actively transmitting? And what is busy, state in [rx,tx,txwait] or waiting for tx (including rx if receiving while waiting for tx) or ...?

And second is how to render this in hopglass? I'd consider to have a bar rx|tx|wait|free, if we can calculate txwait from these values

**Comment by rotanid** [comment]
i'd prefer a bar showing the utilisation of the nodes frequency in percent from 0 to 100

**Comment by corny** [comment]
The `enum nl80211_survey_info` in [nl80211.h](http://lxr.free-electrons.com/source/include/uapi/linux/nl80211.h?v=4.4#L2935) explains the values:

* `NL80211_SURVEY_INFO_TIME`: amount of time (in ms) that the radio was turned on (on channel or globally)
* `NL80211_SURVEY_INFO_TIME_BUSY`: amount of the time the primary channel was sensed busy (either due to activity or energy detect)
* `NL80211_SURVEY_INFO_TIME_RX`: amount of time the radio spent receiving data (on channel or globally)
* `NL80211_SURVEY_INFO_TIME_TX`: amount of time the radio spent transmitting data (on channel or globally)

We use these values to derive the channel utilisation in our [respond-collector](https://github.com/FreifunkBremen/respond-collector/blob/master/data/airtime.go#L52). We use Grafana to create [a fancy graph](https://grafana.ffhb.de/dashboard/db/ort-airtime-kirchweg?panelId=1&fullscreen&from=now-12h&to=now).

**Comment by mar-v-in** [comment]
By analyzing the actual values as provided by ffhb, I came to the conclusion that `busy = rx + tx + wait`. Thus we can calculate `wait = busy - rx - tx` if we want to have a bar that separates different usages. If we don't do display separate usages, we can just bar `busy / active` to have a estimate for the "airtime".

**Comment by Adorfer** [comment]
anway, in https://map.ffdus.de/#!v:g there is now a testbed with at least 40 routers supplying data, inc. some with 5GHz and some in massive wifimesh-scenarios, in order to go for all types of "edge cases".

![grafik](https://cloud.githubusercontent.com/assets/10302493/23111347/56e3a2de-f728-11e6-904c-139856593287.png)

**Comment by Vogelbecker** [comment]
Any updates for this? 
I just build a firmware with gluon-respondd-airtime. As i already use hopglass-server i would be great if the airtime would be collected too.
We could use our network for testing if needed.

Greetings

**Comment by Adorfer** [comment]
What is missing on your part? I can see the airtime at least for the ffffm-airtime package version. 
Do you haven an example where it's not turning?

**Comment by rotanid** [comment]
this ticket is about the upstream package gluon-respondd-airtime - as one can read in the title ;-)

**Comment by Vogelbecker** [comment]
The airtime-data, generated from gluon-respondd-airtime is visible in my http://vpn1.freifunk-einbeck.de:4000/raw.json
But these data will not be shown here http://vpn1.freifunk-einbeck.de:4000/metrics
I think the syntax is diffrent from the upstream package. 
I tried something like this: https://pastebin.com/xQM5R8yX
But my js skills are too bad :-( I am going to try it myself and post a solution, if i found it.

**Comment by rubo77** [comment]
So is there an old externally airtime package that works together with hopglass?

**Comment by collimas** [comment]
Sorry for writing to this old thread, but what exactly is missing to implement support for the respondd-module-airtime package in Hopglass?

**Comment by petabyteboy** [comment]
This is now supported

**Comment by RalfJung** [comment]
For future reference, I guess the commit is https://github.com/hopglass/hopglass-server/commit/da1287e19e7a731013dd78859321b5afa36e243c.

**Comment by petabyteboy** [comment]
Yes, you would also need 78a1349ae209a1175c11bca866c2e4f8475132b7 on the client.
