### ISSUE TITLE
l2tp-nodes on 2016.2.3 report broken (-> causing empty infobox in hopglass client)

### ISSUE THREAD

**Issue by Adorfer** [hopglass/hopglass-server#84]
since gluon 2016.2.2/.3 there is no nodeinfo-box available on nodes using l2tp (ffrl-tunneldigger-package)

https://map.ffdus.de/#!n:e894f6519496

e.g. "Margarete Franke". 

![grafik](https://cloud.githubusercontent.com/assets/10302493/22931342/8d79257a-f2c4-11e6-8ae4-b73f814403aa.png)

nodes.json shows a mixed set of data "before update" and "after update to 2016.2"

"mac":"e8:94:f6:51:94:96"},"owner":{"contact":"adorfer@nadeshda.org"},"system":{"site_code":"ffdus"},"node_id":"e894f6519496","hostname":"Margarete-Franke","hardware":{"model":"TP-Link TL-WR841N/ND v9","nproc":1}},"flags":{"online":true},"statistics":{"uptime":5384.92,"gateway":"ca:b1:e3:ca:b1:e7","gateway_nexthop":"cab1e9cab1e0","memory_usage":0.7969126186092621,"rootfs_usage":0.6771,"clients":3,"loadavg":0.04},"lastseen":"2017-02-14T13:42:07.742Z","firstseen":"2016-02-23T20:36:03.232Z"},{"nodeinfo":{"software":{"autoupdater":{"wifi-fallback":true,"branch":"stable","enabled":true},"batman-adv":{"version":"2016.0","compat":15},"fastd":{"version":"v18","enabled":true},"firmware":{"base":"gluon-v2016.1-128-g40d087d","release":"2016051602-sta"},"status-page":{"api":1}},"network":{"addresses":["fe80::62e3:27ff:fe60:1584","fda0:747e:ab29:9375:62e3:27ff:fe60:1584"],"mesh":{"bat0":{"interfaces":{"wireless":["fe:31:b5:a4:3f:74"],"tunnel":["fe:31:b5:a4:3f:70"]}}}

**Comment by anoymouserver** [comment]
The problem is caused by the resolution of the node gateway in the [`showGateway` function in the hopglass](https://github.com/plumpudding/hopglass/blob/master/lib/infobox/node.js#L316).

The `dictGet(nh.node.statistics, ["gateway"])` ([line 332](https://github.com/plumpudding/hopglass/blob/master/lib/infobox/node.js#L332)) returns a `null` value so the `.id` after it causes a TypeError.

@mar-v-in this part of the code is written by you ... have you any idea how to solve this? I would probably need much longer..

**Comment by mar-v-in** [comment]
@Adorfer can you try out adding the change proposed in https://github.com/mar-v-in/hopglass/commit/c0f4231d3a69cc328f80441803eeb85d1f26b5fd

It would also be possible to add the mac address ca:b1:e3:ca:b1:e7 (which is apparently used) to the corresponding node via its respondd or aliases.json

**Comment by Adorfer** [comment]
got fixed in the client: 
https://github.com/plumpudding/hopglass/commit/b2c2627d73936efbea7723ba022a9e714ec1d4ed
